package main

import (
	"bytes"
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

const initUsage = `Usage: slint-gate init [flags]

Generates a .slint/policy.yaml with sensible defaults for kubebuilder operators
and prints a SessionConfig code snippet to get started.

Flags:
`

// rbacTemplate is the namespace-scoped RBAC manifest for the curl-pod scraping approach.
const rbacTemplate = `# RBAC for kube-slint curl-pod scraping
# Generated by: slint-gate init --emit-rbac
# Apply with: kubectl apply -f rbac-slint.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-slint-scraper
  namespace: {{ .Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-slint-scraper
  namespace: {{ .Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-slint-scraper
  namespace: {{ .Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-slint-scraper
subjects:
  - kind: ServiceAccount
    name: kube-slint-scraper
    namespace: {{ .Namespace }}
`

// policyTemplate is the default policy.yaml for a kubebuilder operator.
// Thresholds align with DefaultV3Specs / BaselineV3Specs.
const policyTemplate = `# .slint/policy.yaml
# Generated by: slint-gate init
# Generated at: {{ .GeneratedAt }}
{{ if .Profile }}# Profile:      {{ .Profile }}
{{ end }}{{ if .ServiceName }}# Namespace:    {{ .Namespace }}
# Service:      {{ .ServiceName }}
{{ end }}
# Adjust thresholds after your first successful E2E run.
# See: https://github.com/HeaInSeo/kube-slint

schema_version: "slint.policy.v1"

thresholds:
  # Operator must perform at least one reconcile during the session.
  - name: "reconcile_total_delta_min"
    metric: "reconcile_total_delta"
    operator: ">="
    value: 1

  # Reconcile errors must be zero.
  - name: "reconcile_error_delta_max"
    metric: "reconcile_error_delta"
    operator: "=="
    value: 0

  # Workqueue must drain by session end.
  - name: "workqueue_depth_end_max"
    metric: "workqueue_depth_end"
    operator: "<="
    value: 0

  # Workqueue retries should stay at zero.
  - name: "workqueue_retries_total_delta_max"
    metric: "workqueue_retries_total_delta"
    operator: "=="
    value: 0

  # API server must not throttle the operator (429 rate-limit).
  - name: "rest_client_429_delta_max"
    metric: "rest_client_429_delta"
    operator: "=="
    value: 0

  # API server must return no 5xx errors.
  - name: "rest_client_5xx_delta_max"
    metric: "rest_client_5xx_delta"
    operator: "=="
    value: 0

regression:
  # Enable after your first baseline is stored.
  enabled: false
  tolerance_percent: 10

reliability:
  required: false
  min_level: "partial"

coverage:
  # Keep true to fail on measured SLIs that are neither gated nor marked informational.
  required: true
  informational:
    - "reconcile_success_delta"
    - "workqueue_adds_total_delta"
    - "rest_client_requests_total_delta"

promote_to_fail:
  - "threshold_miss"
  - "coverage_gap"
  # Uncomment after baseline is established:
  # - "regression_detected"
`

// sessionSnippet is the Go code snippet printed to stdout.
const sessionSnippet = `
// ── SessionConfig snippet ──────────────────────────────────────────────────
// Add this to your E2E test file (e.g., suite_test.go or e2e_test.go).
//
// import "github.com/HeaInSeo/kube-slint/pkg/slint"

sess := slint.NewSession(slint.SessionConfig{
    Namespace:          "{{ .Namespace }}",
    MetricsServiceName: "{{ .ServiceName }}",
    ServiceAccountName: "kube-slint-scraper",
    ArtifactsDir:       "artifacts",
    Specs:              slint.DefaultSpecs(),
    // Uncomment only if your metrics endpoint uses a self-signed cert you
    // can't otherwise trust (e.g. a local dev cluster):
    // DangerouslySkipTLSVerify: true,
})
sess.Start()
// ... run your E2E scenario here ...
sess.End(ctx)

// Then run the gate:
//   make slint-gate
//   ./bin/slint-gate --policy .slint/policy.yaml --exit-on FAIL
// ──────────────────────────────────────────────────────────────────────────
`

type initTemplateData struct {
	GeneratedAt string
	Namespace   string
	ServiceName string
	Profile     string
}

func runInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.Usage = func() {
		fmt.Fprint(os.Stderr, initUsage)
		fs.PrintDefaults()
	}
	namespace := fs.String("namespace", "", "Target namespace for metrics service discovery (optional)")
	service := fs.String("service", "", "MetricsServiceName override; skips auto-discovery")
	output := fs.String("output", filepath.Join(".slint", "policy.yaml"), "Output path for policy.yaml")
	emitRBAC := fs.String("emit-rbac", "", "Write RBAC manifest (ServiceAccount + Role + RoleBinding) to this path")
	profile := fs.String("profile", "", "Onboarding profile preset (currently supported: kubebuilder-operator). Omit to keep today's default init behavior.")
	force := fs.Bool("force", false, "Overwrite --output (and --emit-rbac, if set) if they already exist")

	if err := fs.Parse(args); err != nil {
		return err
	}

	profileName := strings.TrimSpace(*profile)
	if profileName != "" && !isSupportedProfile(profileName) {
		return fmt.Errorf("unknown profile %q (supported: kubebuilder-operator)", profileName)
	}

	rbacPath := strings.TrimSpace(*emitRBAC)
	if !*force {
		if _, statErr := os.Stat(*output); statErr == nil {
			return fmt.Errorf("%s already exists; pass --force to overwrite", *output)
		}
		if rbacPath != "" {
			if _, statErr := os.Stat(rbacPath); statErr == nil {
				return fmt.Errorf("%s already exists; pass --force to overwrite", rbacPath)
			}
		}
	}

	ns := strings.TrimSpace(*namespace)
	svcName, candidates, discoverErr := resolveServiceName(ns, strings.TrimSpace(*service))

	data := initTemplateData{
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		Namespace:   ns,
		ServiceName: svcName,
		Profile:     profileName,
	}

	if profileName != "" {
		fmt.Printf("Initialized kube-slint for profile: %s\n", profileName)
	}

	if err := writePolicyFile(*output, data); err != nil {
		return fmt.Errorf("write policy file: %w", err)
	}

	fmt.Printf("✓ policy.yaml written → %s\n", *output)
	printDiscoveryResult(ns, candidates, discoverErr)

	if rbacPath != "" {
		if err := writeRBACManifest(rbacPath, snippetData(data)); err != nil {
			return fmt.Errorf("write RBAC manifest: %w", err)
		}
		fmt.Printf("✓ RBAC manifest written → %s\n", rbacPath)
		fmt.Printf("  Apply with: kubectl apply -f %s\n", rbacPath)
	}

	return printSessionSnippet(snippetData(data))
}

func resolveServiceName(ns, override string) (string, []string, error) {
	if override != "" {
		return override, nil, nil
	}
	if ns == "" {
		return "", nil, nil
	}
	candidates, err := discoverMetricsServices(ns)
	if err != nil {
		return "", nil, err
	}
	if len(candidates) > 0 {
		return candidates[0], candidates, nil
	}
	return "", candidates, nil
}

func printDiscoveryResult(ns string, candidates []string, discoverErr error) {
	if ns == "" {
		return
	}
	if discoverErr != nil {
		fmt.Printf("  could not auto-detect metrics services in namespace %q: %v\n", ns, discoverErr)
		fmt.Printf("  run: kubectl get svc -n %s\n", ns)
		fmt.Printf("  then re-run: slint-gate init --namespace %s --service <name>\n", ns)
		return
	}
	if len(candidates) > 0 {
		fmt.Printf("✓ discovered metrics services in namespace %q:\n", ns)
		for i, c := range candidates {
			marker := "  "
			if i == 0 {
				marker = "→ "
			}
			fmt.Printf("  %s%s\n", marker, c)
		}
		return
	}
	fmt.Printf("  no metrics services auto-detected in namespace %q\n", ns)
	fmt.Printf("  run: kubectl get svc -n %s\n", ns)
	fmt.Printf("  then re-run: slint-gate init --namespace %s --service <name>\n", ns)
}

func snippetData(data initTemplateData) initTemplateData {
	if data.ServiceName == "" {
		data.ServiceName = "<YOUR_METRICS_SERVICE_NAME>"
	}
	if data.Namespace == "" {
		data.Namespace = "<YOUR_NAMESPACE>"
	}
	return data
}

// discoverMetricsServices lists services in the namespace and returns candidates
// whose name suggests they expose /metrics (heuristic: contains "metrics" or
// "controller-manager", or name ends with known kubebuilder suffix). A non-nil
// error means the kubectl call itself failed (not found on PATH, no cluster
// access, timeout, etc.) — distinct from a nil error with zero candidates,
// which means kubectl ran fine but found nothing metrics-shaped.
func discoverMetricsServices(namespace string) ([]string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	out, err := exec.CommandContext(ctx, "kubectl", "get", "svc",
		"-n", namespace,
		"-o", "jsonpath={range .items[*]}{.metadata.name}{'\\n'}{end}",
	).Output()
	if err != nil {
		return nil, describeKubectlError(err)
	}

	var candidates []string
	for _, name := range strings.Split(string(out), "\n") {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		if isMetricsServiceCandidate(name) {
			candidates = append(candidates, name)
		}
	}
	return candidates, nil
}

// describeKubectlError extracts a concise, single-line reason from a failed
// kubectl invocation: an ExitError surfaces kubectl's own stderr (e.g. "the
// server doesn't have a resource type", "Unauthorized"); anything else (not
// found on PATH, context deadline exceeded) surfaces Go's own error text.
func describeKubectlError(err error) error {
	var exitErr *exec.ExitError
	if errors.As(err, &exitErr) {
		if msg := strings.TrimSpace(string(exitErr.Stderr)); msg != "" {
			return fmt.Errorf("kubectl get svc: %s", msg)
		}
	}
	return fmt.Errorf("kubectl get svc: %w", err)
}

func isMetricsServiceCandidate(name string) bool {
	lower := strings.ToLower(name)
	patterns := []string{"metrics", "controller-manager", "manager-service"}
	for _, p := range patterns {
		if strings.Contains(lower, p) {
			return true
		}
	}
	return false
}

func writePolicyFile(path string, data initTemplateData) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	tmpl, err := template.New("policy").Parse(policyTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	// kube-slint-no-stat-before-write: single-user local CLI artifact write
	// (the --output overwrite-refusal check in runInit), not a shared/multi-tenant race.
	// nosemgrep
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func writeRBACManifest(path string, data initTemplateData) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmpl, err := template.New("rbac").Parse(rbacTemplate)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}
	// kube-slint-no-stat-before-write: single-user local CLI artifact write
	// (the --emit-rbac overwrite-refusal check in runInit), not a shared/multi-tenant race.
	// nosemgrep
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func printSessionSnippet(data initTemplateData) error {
	tmpl, err := template.New("snippet").Parse(sessionSnippet)
	if err != nil {
		return err
	}
	return tmpl.Execute(os.Stdout, data)
}
