package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

const initUsage = `Usage: slint-gate init [flags]

Generates a .slint/policy.yaml with sensible defaults for kubebuilder operators
and prints a SessionConfig code snippet to get started.

Flags:
`

// rbacTemplate is the RBAC manifest for the curl-pod scraping approach.
const rbacTemplate = `# RBAC for kube-slint curl-pod scraping
# Generated by: slint-gate init --emit-rbac
# Apply with: kubectl apply -f rbac-slint.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-slint-scraper
  namespace: {{ .Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-slint-scraper
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-slint-scraper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-slint-scraper
subjects:
  - kind: ServiceAccount
    name: kube-slint-scraper
    namespace: {{ .Namespace }}
`

// policyTemplate is the default policy.yaml for a kubebuilder operator.
// Thresholds align with DefaultV3Specs / BaselineV3Specs.
const policyTemplate = `# .slint/policy.yaml
# Generated by: slint-gate init
# Generated at: {{ .GeneratedAt }}
{{ if .ServiceName }}# Namespace:    {{ .Namespace }}
# Service:      {{ .ServiceName }}
{{ end }}
# Adjust thresholds after your first successful E2E run.
# See: https://github.com/HeaInSeo/kube-slint

schema_version: "slint.policy.v1"

thresholds:
  # Operator must perform at least one reconcile during the session.
  - name: "reconcile_total_delta_min"
    metric: "reconcile_total_delta"
    operator: ">="
    value: 1

  # Reconcile errors must be zero.
  - name: "reconcile_error_delta_max"
    metric: "reconcile_error_delta"
    operator: "=="
    value: 0

  # Workqueue must drain by session end.
  - name: "workqueue_depth_end_max"
    metric: "workqueue_depth_end"
    operator: "<="
    value: 0

  # API server must not throttle the operator (429 rate-limit).
  - name: "rest_client_429_delta_max"
    metric: "rest_client_429_delta"
    operator: "=="
    value: 0

  # API server must return no 5xx errors.
  - name: "rest_client_5xx_delta_max"
    metric: "rest_client_5xx_delta"
    operator: "=="
    value: 0

regression:
  # Enable after your first baseline is stored.
  enabled: false
  tolerance_percent: 10

reliability:
  required: false
  min_level: "partial"

fail_on:
  - "threshold_miss"
  # Uncomment after baseline is established:
  # - "regression_detected"
`

// sessionSnippet is the Go code snippet printed to stdout.
const sessionSnippet = `
// ── SessionConfig snippet ──────────────────────────────────────────────────
// Add this to your E2E test file (e.g., suite_test.go or e2e_test.go).
//
// import "github.com/HeaInSeo/kube-slint/test/e2e/harness"

sess := harness.NewSession(harness.SessionConfig{
    Namespace:             "{{ .Namespace }}",
    MetricsServiceName:    "{{ .ServiceName }}",
    ArtifactsDir:          "artifacts",
    Specs:                 harness.DefaultV3Specs(),
    TLSInsecureSkipVerify: true,
})
sess.Start()
// ... run your E2E scenario here ...
sess.End(ctx)

// Then run the gate:
//   make slint-gate
//   ./bin/slint-gate --policy .slint/policy.yaml
// ──────────────────────────────────────────────────────────────────────────
`

type initTemplateData struct {
	GeneratedAt string
	Namespace   string
	ServiceName string
}

func runInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.Usage = func() {
		fmt.Fprint(os.Stderr, initUsage)
		fs.PrintDefaults()
	}
	namespace := fs.String("namespace", "", "Target namespace for metrics service discovery (optional)")
	service := fs.String("service", "", "MetricsServiceName override; skips auto-discovery")
	output := fs.String("output", filepath.Join(".slint", "policy.yaml"), "Output path for policy.yaml")
	emitRBAC := fs.String("emit-rbac", "", "Write RBAC manifest (ServiceAccount + ClusterRole + Binding) to this path")

	if err := fs.Parse(args); err != nil {
		return err
	}

	ns := strings.TrimSpace(*namespace)
	svcName, candidates := resolveServiceName(ns, strings.TrimSpace(*service))

	data := initTemplateData{
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		Namespace:   ns,
		ServiceName: svcName,
	}

	if err := writePolicyFile(*output, data); err != nil {
		return fmt.Errorf("write policy file: %w", err)
	}

	fmt.Printf("✓ policy.yaml written → %s\n", *output)
	printDiscoveryResult(ns, candidates)

	if rbacPath := strings.TrimSpace(*emitRBAC); rbacPath != "" {
		if err := writeRBACManifest(rbacPath, snippetData(data)); err != nil {
			return fmt.Errorf("write RBAC manifest: %w", err)
		}
		fmt.Printf("✓ RBAC manifest written → %s\n", rbacPath)
		fmt.Printf("  Apply with: kubectl apply -f %s\n", rbacPath)
	}

	return printSessionSnippet(snippetData(data))
}

func resolveServiceName(ns, override string) (string, []string) {
	if override != "" {
		return override, nil
	}
	if ns == "" {
		return "", nil
	}
	candidates := discoverMetricsServices(ns)
	if len(candidates) > 0 {
		return candidates[0], candidates
	}
	return "", candidates
}

func printDiscoveryResult(ns string, candidates []string) {
	if ns == "" {
		return
	}
	if len(candidates) > 0 {
		fmt.Printf("✓ discovered metrics services in namespace %q:\n", ns)
		for i, c := range candidates {
			marker := "  "
			if i == 0 {
				marker = "→ "
			}
			fmt.Printf("  %s%s\n", marker, c)
		}
		return
	}
	fmt.Printf("  no metrics services auto-detected in namespace %q\n", ns)
	fmt.Printf("  run: kubectl get svc -n %s\n", ns)
	fmt.Printf("  then re-run: slint-gate init --namespace %s --service <name>\n", ns)
}

func snippetData(data initTemplateData) initTemplateData {
	if data.ServiceName == "" {
		data.ServiceName = "<YOUR_METRICS_SERVICE_NAME>"
	}
	if data.Namespace == "" {
		data.Namespace = "<YOUR_NAMESPACE>"
	}
	return data
}

// discoverMetricsServices lists services in the namespace and returns candidates
// whose name suggests they expose /metrics (heuristic: contains "metrics" or
// "controller-manager", or name ends with known kubebuilder suffix).
func discoverMetricsServices(namespace string) []string {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	out, err := exec.CommandContext(ctx, "kubectl", "get", "svc",
		"-n", namespace,
		"-o", "jsonpath={range .items[*]}{.metadata.name}{'\\n'}{end}",
	).Output()
	if err != nil {
		return nil
	}

	var candidates []string
	for _, name := range strings.Split(string(out), "\n") {
		name = strings.TrimSpace(name)
		if name == "" {
			continue
		}
		if isMetricsServiceCandidate(name) {
			candidates = append(candidates, name)
		}
	}
	return candidates
}

func isMetricsServiceCandidate(name string) bool {
	lower := strings.ToLower(name)
	patterns := []string{"metrics", "controller-manager", "manager-service"}
	for _, p := range patterns {
		if strings.Contains(lower, p) {
			return true
		}
	}
	return false
}

func writePolicyFile(path string, data initTemplateData) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	tmpl, err := template.New("policy").Parse(policyTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func writeRBACManifest(path string, data initTemplateData) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmpl, err := template.New("rbac").Parse(rbacTemplate)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func printSessionSnippet(data initTemplateData) error {
	tmpl, err := template.New("snippet").Parse(sessionSnippet)
	if err != nil {
		return err
	}
	return tmpl.Execute(os.Stdout, data)
}
