package main

import "fmt"

// profileCandidate is one SLI a profile expects to see in a measurement
// summary, along with the default threshold rule recommend-policy generates
// for it and the reasoning inspect/recommend-policy print to the user.
type profileCandidate struct {
	ID       string
	Operator string
	Value    float64
	Reason   string

	// Tier is "core" (always recommended as an active threshold once
	// measured, regardless of --strictness) or "noisy" (CI-environment
	// sensitive; --strictness governs whether it becomes an active
	// threshold or stays commented out).
	Tier string
}

const (
	tierCore  = "core"
	tierNoisy = "noisy"
)

// kubebuilderOperatorCandidates mirrors the thresholds already generated by
// `init.go`'s policyTemplate — same IDs, same operator/value pairs — so
// inspect/recommend-policy describe exactly what init already recommends.
var kubebuilderOperatorCandidates = []profileCandidate{
	{
		ID: "reconcile_total_delta", Operator: ">=", Value: 1, Tier: tierCore,
		Reason: "Operator must perform at least one reconcile during the session.",
	},
	{
		ID: "reconcile_error_delta", Operator: "==", Value: 0, Tier: tierCore,
		Reason: "A healthy operator E2E run should not introduce reconcile errors.",
	},
	{
		ID: "workqueue_depth_end", Operator: "<=", Value: 0, Tier: tierCore,
		Reason: "The workqueue should be drained at the end of the test scenario.",
	},
	{
		ID: "rest_client_5xx_delta", Operator: "==", Value: 0, Tier: tierCore,
		Reason: "5xx responses during the test indicate unstable Kubernetes API interactions.",
	},
	{
		ID: "rest_client_429_delta", Operator: "==", Value: 0, Tier: tierNoisy,
		Reason: "Client-side throttling may indicate API pressure or controller behavior changes.",
	},
	{
		ID: "workqueue_retries_total_delta", Operator: "==", Value: 0, Tier: tierNoisy,
		Reason: "Retries may be environment-dependent; confirm the signal is stable before enforcing it.",
	},
}

// profileCandidates returns the SLI candidate list for a supported profile.
func profileCandidates(profile string) ([]profileCandidate, error) {
	switch profile {
	case "kubebuilder-operator":
		return kubebuilderOperatorCandidates, nil
	default:
		return nil, fmt.Errorf("unknown profile %q (supported: kubebuilder-operator)", profile)
	}
}

// isSupportedProfile reports whether name is a known profile.
func isSupportedProfile(name string) bool {
	_, err := profileCandidates(name)
	return err == nil
}
