package main

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// profileCandidate is one SLI a profile expects to see in a measurement
// summary, along with the default threshold rule recommend-policy generates
// for it and the reasoning inspect/recommend-policy print to the user.
type profileCandidate struct {
	ID       string
	Operator string
	Value    float64
	Reason   string

	// Tier is one of:
	//   "core"          — always recommended as an active threshold once
	//                      measured, regardless of --strictness.
	//   "noisy"         — CI-environment sensitive; --strictness governs
	//                      whether it becomes an active threshold or stays
	//                      commented out.
	//   "informational" — a raw activity counter with no principled
	//                      pass/fail threshold (e.g. a total-requests
	//                      count); always shown to the user but never
	//                      promoted to an active rule, regardless of
	//                      --strictness or measurement.
	Tier string
}

const (
	tierCore          = "core"
	tierNoisy         = "noisy"
	tierInformational = "informational"
)

var validProfileOperators = map[string]bool{
	"<": true, "<=": true, ">": true, ">=": true, "==": true,
}

var validProfileTiers = map[string]bool{
	tierCore: true, tierNoisy: true, tierInformational: true,
}

// kubebuilderOperatorCandidates mirrors the thresholds already generated by
// `init.go`'s policyTemplate — same IDs, same operator/value pairs — so
// inspect/recommend-policy describe exactly what init already recommends.
var kubebuilderOperatorCandidates = []profileCandidate{
	{
		ID: "reconcile_total_delta", Operator: ">=", Value: 1, Tier: tierCore,
		Reason: "Operator must perform at least one reconcile during the session.",
	},
	{
		ID: "reconcile_error_delta", Operator: "==", Value: 0, Tier: tierCore,
		Reason: "A healthy operator E2E run should not introduce reconcile errors.",
	},
	{
		ID: "workqueue_depth_end", Operator: "<=", Value: 0, Tier: tierCore,
		Reason: "The workqueue should be drained at the end of the test scenario.",
	},
	{
		ID: "rest_client_5xx_delta", Operator: "==", Value: 0, Tier: tierCore,
		Reason: "5xx responses during the test indicate unstable Kubernetes API interactions.",
	},
	{
		ID: "rest_client_429_delta", Operator: "==", Value: 0, Tier: tierNoisy,
		Reason: "Client-side throttling may indicate API pressure or controller behavior changes.",
	},
	{
		ID: "workqueue_retries_total_delta", Operator: "==", Value: 0, Tier: tierNoisy,
		Reason: "Retries may be environment-dependent; confirm the signal is stable before enforcing it.",
	},
	{
		ID: "reconcile_success_delta", Tier: tierInformational,
		Reason: "Raw count of successful reconciles; no principled pass/fail threshold, useful as context only.",
	},
	{
		ID: "workqueue_adds_total_delta", Tier: tierInformational,
		Reason: "Raw count of items added to the workqueue; an activity volume, not itself a pass/fail signal.",
	},
	{
		ID: "rest_client_requests_total_delta", Tier: tierInformational,
		Reason: "Raw count of Kubernetes API requests; useful as context for rest_client_429_delta/5xx_delta, not gateable on its own.",
	},
}

// profileCandidates returns the SLI candidate list for a supported built-in profile.
func profileCandidates(profile string) ([]profileCandidate, error) {
	switch profile {
	case "kubebuilder-operator":
		return kubebuilderOperatorCandidates, nil
	default:
		return nil, fmt.Errorf("unknown profile %q (supported: kubebuilder-operator)", profile)
	}
}

// isSupportedProfile reports whether name is a known built-in profile.
func isSupportedProfile(name string) bool {
	_, err := profileCandidates(name)
	return err == nil
}

// customProfileDoc is the on-disk schema for a local custom profile file
// (slint.profile.v1). It deliberately mirrors profileCandidate's shape
// rather than the richer per-strictness-override schema sometimes discussed
// for this feature, since recommend-policy's strictness logic already
// operates on a global --strictness flag + per-candidate Tier, not per-rule
// per-strictness value maps.
type customProfileDoc struct {
	SchemaVersion string                      `yaml:"schema_version"`
	Name          string                      `yaml:"name"`
	Description   string                      `yaml:"description"`
	Candidates    []customProfileCandidateDoc `yaml:"candidates"`
}

type customProfileCandidateDoc struct {
	ID       string  `yaml:"id"`
	Operator string  `yaml:"operator"`
	Value    float64 `yaml:"value"`
	Tier     string  `yaml:"tier"`
	Reason   string  `yaml:"reason"`
}

const customProfileSchemaVersion = "slint.profile.v1"

// loadCustomProfile reads and validates a local custom profile file, returning
// its candidate list and display name.
func loadCustomProfile(path string) ([]profileCandidate, string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, "", fmt.Errorf("could not read profile file %s: %w", path, err)
	}
	var doc customProfileDoc
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, "", fmt.Errorf("could not parse profile file %s: %w", path, err)
	}
	if doc.SchemaVersion != customProfileSchemaVersion {
		return nil, "", fmt.Errorf("profile file %s: unsupported schema_version %q (want %q)", path, doc.SchemaVersion, customProfileSchemaVersion)
	}
	if len(doc.Candidates) == 0 {
		return nil, "", fmt.Errorf("profile file %s: no candidates defined", path)
	}

	candidates := make([]profileCandidate, 0, len(doc.Candidates))
	for i, c := range doc.Candidates {
		id := strings.TrimSpace(c.ID)
		if id == "" {
			return nil, "", fmt.Errorf("profile file %s: candidates[%d].id is empty", path, i)
		}
		tier := strings.TrimSpace(c.Tier)
		if tier == "" {
			tier = tierCore
		}
		if !validProfileTiers[tier] {
			return nil, "", fmt.Errorf("profile file %s: candidates[%d] has unrecognized tier %q (supported: core, noisy, informational)", path, i, c.Tier)
		}
		if tier != tierInformational && !validProfileOperators[c.Operator] {
			return nil, "", fmt.Errorf("profile file %s: candidates[%d] has unsupported operator %q (supported: <, <=, >, >=, ==)", path, i, c.Operator)
		}
		candidates = append(candidates, profileCandidate{
			ID: id, Operator: c.Operator, Value: c.Value, Reason: c.Reason, Tier: tier,
		})
	}

	name := strings.TrimSpace(doc.Name)
	if name == "" {
		name = path
	}
	return candidates, name, nil
}

// resolveProfileCandidates implements the profile resolution order:
//  1. --profile-file, if explicitly given, always wins.
//  2. .slint/profiles/<profileName>.yaml, if present (repo-local convention).
//  3. A built-in profile looked up by name.
func resolveProfileCandidates(profileFileFlag, profileName string) ([]profileCandidate, string, error) {
	if f := strings.TrimSpace(profileFileFlag); f != "" {
		return loadCustomProfile(f)
	}
	localPath := ".slint/profiles/" + profileName + ".yaml"
	if _, err := os.Stat(localPath); err == nil {
		return loadCustomProfile(localPath)
	}
	candidates, err := profileCandidates(profileName)
	return candidates, profileName, err
}
