package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/HeaInSeo/kube-slint/pkg/slo/summary"
)

const recommendPolicyUsage = `Usage: slint-gate recommend-policy [flags]

Generates a .slint/policy.yaml draft from a measured sli-summary.json: SLIs
that were actually measured become active threshold rules; SLIs the profile
expects but weren't measured are recorded as comments, not active rules.

Flags:
`

var supportedStrictness = map[string]bool{
	"strict":       true,
	"conservative": true,
	"lenient":      true,
}

// recommendPolicyTemplate mirrors init.go's policyTemplate structurally, but
// the thresholds/comment blocks are pre-rendered in Go (see
// renderActiveThresholds/renderCommentedCandidates) rather than expressed as
// template range logic, to keep the generated YAML's whitespace predictable.
const recommendPolicyTemplate = `# .slint/policy.yaml
# Generated by: slint-gate recommend-policy
# Generated at: {{ .GeneratedAt }}
# Profile:      {{ .Profile }}
# Strictness:   {{ .Strictness }}
#
# kube-slint is a shift-left SLI gate: this checks development-time
# operational signals observed during your E2E test, not production SLOs.
# Review and adjust before relying on this in CI.

schema_version: "slint.policy.v1"

thresholds:
{{ .ActiveBlock }}
{{ .CommentedBlock }}
regression:
  # Enable after you approve a healthy run as a baseline.
  enabled: false
  tolerance_percent: 10

reliability:
  required: false
  min_level: "partial"

promote_to_fail:
  - "threshold_miss"
  # Uncomment after baseline is established:
  # - "regression_detected"
`

type recommendedThreshold struct {
	Name, Metric, Operator, Reason string
	Value                          float64
	RelaxNote                      string
	MismatchNote                   string
}

type recommendPolicyTemplateData struct {
	GeneratedAt, Profile, Strictness string
	ActiveBlock, CommentedBlock      string
}

func runRecommendPolicy(args []string) error {
	fs := flag.NewFlagSet("recommend-policy", flag.ContinueOnError)
	fs.Usage = func() {
		fmt.Fprint(os.Stderr, recommendPolicyUsage)
		fs.PrintDefaults()
	}
	summaryPath := fs.String("summary", "artifacts/sli-summary.json", "Path to the measurement summary JSON")
	profile := fs.String("profile", "kubebuilder-operator", "Onboarding profile to recommend thresholds for")
	profileFile := fs.String("profile-file", "", "Path to a local custom profile file (overrides --profile)")
	strictness := fs.String("strictness", "conservative", "Threshold strictness: strict | conservative | lenient")
	output := fs.String("output", filepath.Join(".slint", "policy.yaml"), "Output path for the generated policy.yaml")
	force := fs.Bool("force", false, "Overwrite --output if it already exists")
	dryRun := fs.Bool("dry-run", false, "Print the generated policy.yaml to stdout instead of writing it")

	if err := fs.Parse(args); err != nil {
		return err
	}

	candidates, profileName, err := resolveProfileCandidates(*profileFile, strings.TrimSpace(*profile))
	if err != nil {
		return err
	}

	strictnessName := strings.ToLower(strings.TrimSpace(*strictness))
	if !supportedStrictness[strictnessName] {
		return fmt.Errorf("unknown --strictness %q (supported: strict, conservative, lenient)", *strictness)
	}

	s, err := summary.LoadFile(*summaryPath)
	if err != nil {
		return fmt.Errorf("kube-slint could not recommend a policy: %w (run 'slint-gate inspect --summary %s' for details)", err, *summaryPath)
	}

	if !*dryRun {
		if _, statErr := os.Stat(*output); statErr == nil && !*force {
			return fmt.Errorf("%s already exists; pass --force to overwrite or --dry-run to preview", *output)
		}
	}

	measured := make(map[string]*summary.SLIResult, len(s.Results))
	for i := range s.Results {
		measured[s.Results[i].ID] = &s.Results[i]
	}

	active, commented := classifyCandidates(candidates, measured, strictnessName)

	data := recommendPolicyTemplateData{
		GeneratedAt:    time.Now().UTC().Format(time.RFC3339),
		Profile:        profileName,
		Strictness:     strictnessName,
		ActiveBlock:    renderActiveThresholds(active),
		CommentedBlock: renderCommentedCandidates(commented),
	}

	tmpl, err := template.New("recommend-policy").Parse(recommendPolicyTemplate)
	if err != nil {
		return err
	}
	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	if *dryRun {
		fmt.Print(buf.String())
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		return fmt.Errorf("write policy file: %w", err)
	}
	if err := os.WriteFile(*output, []byte(buf.String()), 0o644); err != nil {
		return fmt.Errorf("write policy file: %w", err)
	}

	fmt.Printf("✓ policy.yaml written → %s\n", *output)
	fmt.Println("\nNext:")
	fmt.Printf("  slint-gate --policy %s --measurement-summary %s\n", *output, *summaryPath)

	return nil
}

// classifyCandidates decides, for each profile candidate, whether it becomes
// an active threshold rule or a commented-out entry (and why), per the
// tier/measurement/strictness rules described on profileCandidate.Tier.
func classifyCandidates(candidates []profileCandidate, measured map[string]*summary.SLIResult, strictnessName string) ([]recommendedThreshold, []commentedEntry) {
	var active []recommendedThreshold
	var commented []commentedEntry
	for _, c := range candidates {
		if c.Tier == tierInformational {
			commented = append(commented, commentedEntry{c, "this is an informational SLI — no default threshold is recommended"})
			continue
		}
		if _, ok := measured[c.ID]; !ok {
			commented = append(commented, commentedEntry{c, "missing metric — not measured in the current summary"})
			continue
		}
		if c.Tier == tierNoisy && strictnessName == "lenient" {
			commented = append(commented, commentedEntry{c, "held back by --strictness lenient"})
			continue
		}
		t := recommendedThreshold{
			Name:     c.ID + "_recommended",
			Metric:   c.ID,
			Operator: c.Operator,
			Value:    c.Value,
			Reason:   c.Reason,
		}
		if c.Tier == tierNoisy && strictnessName == "conservative" {
			t.RelaxNote = "    #\n" +
				"    # This SLI can be CI-environment sensitive. If your CI proves this\n" +
				"    # signal is noisy rather than a real regression, consider relaxing this\n" +
				"    # rule only after confirming the source is transient.\n"
		}
		if r, ok := measured[c.ID]; ok && r.Value != nil && violatesDefault(c.Operator, c.Value, *r.Value) {
			t.MismatchNote = fmt.Sprintf(
				"    # ⚠ measured value (%v) does not satisfy this default threshold —\n"+
					"    #   review before relying on this rule in CI.\n", *r.Value)
		}
		active = append(active, t)
	}
	return active, commented
}

func renderActiveThresholds(items []recommendedThreshold) string {
	if len(items) == 0 {
		return ""
	}
	var b strings.Builder
	for _, t := range items {
		fmt.Fprintf(&b, "  - name: %q\n", t.Name)
		fmt.Fprintf(&b, "    metric: %q\n", t.Metric)
		fmt.Fprintf(&b, "    operator: %q\n", t.Operator)
		fmt.Fprintf(&b, "    value: %v\n", t.Value)
		fmt.Fprintf(&b, "    # %s\n", t.Reason)
		if t.MismatchNote != "" {
			b.WriteString(t.MismatchNote)
		}
		if t.RelaxNote != "" {
			b.WriteString(t.RelaxNote)
		}
		b.WriteString("\n")
	}
	return strings.TrimRight(b.String(), "\n")
}

// violatesDefault reports whether measured fails the rule "measured operator
// target" — i.e. whether the candidate's own default threshold is already
// violated by what was actually observed. Mirrors pkg/gate/gate.go's
// compareOp semantics for the 5 supported operators (duplicated locally for
// the same reason as baseline_diff.go's direction helpers: this is a
// CLI-only concern, not worth expanding pkg/gate's public API for).
func violatesDefault(operator string, target, measured float64) bool {
	switch strings.TrimSpace(operator) {
	case "<=", "=<":
		return !(measured <= target)
	case ">=", "=>":
		return !(measured >= target)
	case "<":
		return !(measured < target)
	case ">":
		return !(measured > target)
	case "==", "=":
		return measured != target
	default:
		return false
	}
}

// commentedEntry pairs a candidate not promoted to an active rule with the
// specific reason (missing / informational / held back by strictness), so
// the generated comment block describes each case accurately instead of
// using one generic explanation for all of them.
type commentedEntry struct {
	candidate profileCandidate
	note      string
}

func renderCommentedCandidates(items []commentedEntry) string {
	if len(items) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("\n# Not promoted to an active rule:\n#\n")
	for _, e := range items {
		fmt.Fprintf(&b, "# - %s (%s)\n", e.candidate.ID, e.note)
		fmt.Fprintf(&b, "#   %s\n#\n", e.candidate.Reason)
	}
	return b.String()
}
